### ISSUE TITLE
TRG - Finance Handout Preperation

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Confident-Dental#63]
Kindly create the handout for the finance

**Comment by AkashGleen** [comment]
@sujin1708 

Kindly Check The All The Handout any correction kindly update.

[CDEPL_Book Keeping_HANDOUT_v1.docx](https://github.com/astpl1998/Confident-Dental/files/7047194/CDEPL_Book.Keeping_HANDOUT_v1.docx)
[CDEPL_Fixed Assets_HANDOUT_v1.docx](https://github.com/astpl1998/Confident-Dental/files/7047196/CDEPL_Fixed.Assets_HANDOUT_v1.docx)
[CDEPL_Globle Tax Solution_HANDOUT_v1.docx](https://github.com/astpl1998/Confident-Dental/files/7047197/CDEPL_Globle.Tax.Solution_HANDOUT_v1.docx)
[CDEPL_Management Account_HANDOUT_v1.docx](https://github.com/astpl1998/Confident-Dental/files/7047198/CDEPL_Management.Account_HANDOUT_v1.docx)
[CDEPL_Payable Management_HANDOUT_v1.docx](https://github.com/astpl1998/Confident-Dental/files/7047199/CDEPL_Payable.Management_HANDOUT_v1.docx)
[CDEPL_Receivable Management_HANDOUT_v1.docx](https://github.com/astpl1998/Confident-Dental/files/7047200/CDEPL_Receivable.Management_HANDOUT_v1.docx)

Regards,
Akash

**Comment by raju-kurup** [comment]
Handouts delivered to Confident, so closing this ticket
