### ISSUE TITLE
ISS: Work Order Consumption ARD Issue

### ISSUE THREAD

**Issue by viki18790** [astpl1998/Confident-Dental#67]
@Narendiranath 

When creating a Work order from an Inspection Order, I'm getting the following error, please find the attached screenshot for this error.
![Screenshot_ARD](https://user-images.githubusercontent.com/73546890/132648944-939e01c2-87a3-4b4c-a086-214719ff4e87.png)

**Comment by raju-kurup** [comment]
@Narendiranath : please analyze this issue and advise us

**Comment by Narendiranath** [comment]
@viki18790 

                 Cost type is came 'RE'  instead of '-N/A-'. I changed 'RE' to '-N/A-'.

**Comment by raju-kurup** [comment]
Issue resolved, so closing this ticket
